export const CODIGOS_ERROR = {
  VALIDACION: 400,
  NO_AUTENTICADO: 401,
  SIN_PERMISO: 403,
  NO_ENCONTRADO: 404,
  CONFLICTO: 409,
  INTERNO: 500,
  CSRF: 403,
  INGRESO_BLOQUEADO: 429,
  CONTRASENA_PENDIENTE: 403,
  TERMINOS_PENDIENTES: 403,
  CREDENCIALES_INVALIDAS: 401,
  CONTRASENA_ACTUAL_INCORRECTA: 400,
  CONTRASENA_DEBIL: 400,
  NUMERACION_INICIAL_MENOR: 400,
  NUMERACION_DIGITOS_INSUFICIENTES: 400,
  NUMERACION_AGOTADA: 409,
} as const;
export type CodigoError = keyof typeof CODIGOS_ERROR;
