import type { OtDatos, OtResumenDatos } from '@/features/ots/api';

// OT-0218 del diseño: facturable en Cotizada, 4 tareas, sin bolsa.
export function otDePrueba(cambios: Partial<OtDatos> = {}): OtDatos {
  return {
    id: 21,
    numero: 218,
    codigo: 'OT-0218',
    titulo: 'Regularización de folios de facturación electrónica',
    tipo: 'facturable',
    etapa: 'cotizada',
    estado_facturacion: 'pendiente',
    resolvio_ticket: null,
    creado_en: '2026-09-29T13:02:00.000Z',
    cerrada_en: null,
    ticket: { id: 7, codigo: 'TK-1048', asunto: 'Error al emitir facturas desde el ERP' },
    cliente: { id: 1, nombre: 'Viña Santa Clara', es_interno: false },
    responsable_tecnico: {
      id: 3,
      nombre: 'Sebastián Díaz',
      iniciales: 'SD',
      color_avatar: '#CDEBE6',
    },
    aprobador: null,
    neto: null,
    horas: { estimadas: 10, reales: 4, registradas: 3 },
    inicio: null,
    termino: '2026-10-02',
    vencida: false,
    esperando_cliente: false,
    por_aprobar: false,
    n_mensajes: 0,
    actualizado_en: '2026-09-29T13:40:00.000Z',
    alcance: 'Regularizar los folios del CAF.',
    cliente_id: 1,
    contacto: null,
    oc_cliente: null,
    condicion_pago: null,
    bolsa: null,
    centro_costo: null,
    area_solicitante: null,
    aprobada_por: null,
    aprobada_en: null,
    aprobacion: null,
    n_factura: null,
    facturada_en: null,
    facturada_por: null,
    resumen_cierre: null,
    cerrada_por: null,
    motivo_cancelacion: null,
    cancelada_en: null,
    tareas: [],
    archivos: [],
    ticket_origen: {
      id: 7,
      codigo: 'TK-1048',
      asunto: 'Error al emitir facturas desde el ERP',
      estado: 'en_curso',
      cliente: { id: 1, nombre: 'Viña Santa Clara', es_interno: false },
      responsables: [
        {
          id: 3,
          nombre: 'Sebastián Díaz',
          iniciales: 'SD',
          color_avatar: '#CDEBE6',
          principal: true,
        },
        {
          id: 2,
          nombre: 'Camila Rojas',
          iniciales: 'CR',
          color_avatar: '#F2D7C9',
          principal: false,
        },
      ],
      seguidores: [],
      otras_ots_abiertas: [],
    },
    cotizacion: null,
    costo_interno: null,
    puede_cotizar: false,
    tipo_cambiable: true,
    creado_por: { id: 2, nombre: 'Camila Rojas' },
    ...cambios,
  };
}

export function otResumenDePrueba(cambios: Partial<OtResumenDatos> = {}): OtResumenDatos {
  const { id, numero, codigo, titulo, tipo, etapa, estado_facturacion, ticket, cliente } =
    otDePrueba();
  return {
    id,
    numero,
    codigo,
    titulo,
    tipo,
    etapa,
    estado_facturacion,
    resolvio_ticket: null,
    creado_en: '2026-09-29T13:02:00.000Z',
    cerrada_en: null,
    ticket,
    cliente,
    responsable_tecnico: null,
    aprobador: null,
    neto: null,
    horas: { estimadas: 10, reales: 4, registradas: 3 },
    inicio: null,
    termino: null,
    vencida: false,
    esperando_cliente: false,
    por_aprobar: false,
    n_mensajes: 0,
    actualizado_en: '2026-09-29T13:40:00.000Z',
    ...cambios,
  };
}
